server:
    packages:
        - zsh
        - curl
        - wget
        - vim
        - nano
        - htop
    gems:
        - compass
        - bootstrap-sass
        - font-awesome-sass
synced_folder:
    code:
        source: ~/Code
        target: /var/www
        owner: www-data
        group: www-data
    modules:
        source: ./config/puppet/modules
        target: /etc/puppet/modules
        owner: root
        group: root
vhosts:
    hephaestus:
        servername: hephaestus.dev
        setenv:
            - 'APP_ENV dev'
        docroot: /var/www/hephaestus.dev/www
        directories:
            hephaestus:
                path: /var/www/hephaestus.dev
                options:
                    - Indexes
                    - FollowSymlinks
                    - MultiViews
                allow_override:
                    - All
                require:
                    - 'all granted'
                files_match:
                    hephaestus:
                        path: \.php$
                        sethandler: 'proxy:fcgi://127.0.0.1:9000'
                        custom_fragment: ''
                        provider: filesmatch
                provider: directory
                custom_fragment: ''
php:
    settings:
        version: '54'
    modules:
        php:
            - cli
            - intl
            - mcrypt
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: Europe/Zurich
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfpmpool1:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''