server:
    packages:
        - zsh
        - curl
        - wget
        - vim
        - nano
        - htop
synced_folder:
    code:
        source: ~/Code
        target: /var/www
        owner: www-data
        group: www-data
    modules:
        source: ./config/puppet/modules
        target: /etc/puppet/modules
        owner: root
        group: root
apache:
    vhosts:
        hephaestus:
            servername: hephaestus.dev
            setenv:
                - 'APP_ENV dev'
            path: /var/www/hephaestus
            docroot: /var/www/servername/webroot
php:
    settings:
        version: '54'
    modules:
        php:
            - cli
            - intl
            - mcrypt
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: Europe/Zurich
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfpmpool1:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''