server:
    packages:
        - zsh
        - curl
        - vim
        - nano
        - htop
    gems:
        - compass
        - bootstrap-sass
        - font-awesome-sass
synced_folder:
    code:
        source: ~/Code
        target: /var/www
        owner: www-data
        group: www-data
    modules:
        source: ./config/puppet/modules
        target: /etc/puppet/modules
        owner: root
        group: root
vhosts:
    hephaestus.dev:
        servername: hephaestus.dev
        setenv:
            - 'APP_ENV dev'
        docroot: /var/www/hephaestus.dev/www
    novia.dev:
        servername: novia.dev
        setenv:
            - 'APP_ENV dev'
        docroot: /var/www/novia.dev
php::settings:
    version: '54'
    date.timezone: Europe/Zurich
    Php/display_errors: On
    Php/error_reporting: -1
    session.save_path: /var/lib/php/session
    Php/short_open_tag: On
    Php/expose_php: Off
php::extensions:
    intl: {}
    mcrypt: {}
    curl: {}
    gd: {}
    imap: {}
    mysql: {}
    readline: {}
    sqlite: {}
    xsl: {}
    apc:
        package_prefix: php-
        settings:
          apc.stat: 1
          apc.stat_ctime: 1
php::fpm: true
php::composer: true