import 'nodes/Server.pp'
# import 'nodes/Apache.pp'
# import 'nodes/Nginx.pp'
# import 'nodes/MySQL.pp'
# import 'nodes/PHP.pp'
# import 'nodes/MailCatcher.pp'
# import 'nodes/NodeJS.pp'
# import 'nodes/Java.pp'
import 'nodes/Oh-My-ZSH.pp'